### ISSUE TITLE
Switch API for the Food check

### ISSUE THREAD

**Issue by rhipsime** [rhipsime/cariLOL#32]
Please use Edmame API Key for the Food check page 
File scriptfoodcheck.js
File apikey.js
<img width="967" alt="Screenshot 2024-02-02 at 20 18 55" src="https://github.com/rhipsime/cariLOL/assets/151936395/af80aa4a-6ae8-4862-9012-2db4ae73afe4">

**Comment by Antimio** [comment]
Done. API working and code to extract data completed.
