### ISSUE TITLE
Gender and Extra Search Box needs to be removed

### ISSUE THREAD

**Issue by rhipsime** [rhipsime/cariLOL#44]
These are not required parameters for the calorie calculator
<img width="1071" alt="Screenshot 2024-02-06 at 12 40 21" src="https://github.com/rhipsime/cariLOL/assets/151936395/af46f6d4-1329-4543-8575-28b069cb02d1">

**Comment by DodoID** [comment]
Hi, I have removed the obsolete fields! (commented them out in case we may ned them after all)
